First draft 1501 course guide
pittcsc/pittcswiki pull request #387
Opened 2023-07-23 19:23 UTC by NathanBarta

2023-07-28 20:18 UTC, agrattan0820 commented on src/guides/academics/succeed-in-course-x/succeed-in-1501.md
> +> Don't cheat. It's very easy to catch. Beyond the typical meaning of cheating: *don't cheat yourself*. Did you write some code that you don't fully understand? Figure it out. Do it right.
`It's very easy to catch.` to `It's very easy to get caught."?

2023-07-28 20:19 UTC, agrattan0820 approved these changes
Awesome

2023-08-15 01:26 UTC, FishOfPitt116 requested changes
Overall, really good article that covers a lot of bases when it comes to knowing what 1501 covers and how to approach assignments. Just make the few minor changes and I'll approve :)

2023-08-15 01:26 UTC, FishOfPitt116 commented on src/guides/academics/succeed-in-course-x/succeed-in-1501.md
> +      - Distance metric
With 1503 becoming a requirement, is this still true? Will this be included in 1501? I guess time will tell

2023-08-15 01:26 UTC, FishOfPitt116 commented on src/guides/academics/succeed-in-course-x/succeed-in-1501.md
> +### **Recitations**
Emphasize that you should attend recitation (despite the fact that I may or may not have throughout the semester I took 1501...)

You could also mention that recitation might be required depending on professor

2023-08-15 01:26 UTC, FishOfPitt116 commented on src/guides/academics/succeed-in-course-x/succeed-in-1501.md
> +I'd recommend reading the author's implementations and making sure it lines up with what you read from the book. Once you can draw the connections, move on, or even experiment with alternate implemen
Mention that most profs have author's code that they provide for you as the semester goes on. Sometimes, in Farnan's project specifically, he lets you directly pull from this code for your data structures. So make a point that this should be something that's referenced

2023-08-15 01:26 UTC, FishOfPitt116 commented on src/guides/academics/succeed-in-course-x/succeed-in-1501.md
> +> Don't cheat. It's very easy to catch. Beyond the typical meaning of cheating: *don't cheat yourself*. Did you write some code that you don't fully understand? Figure it out. Do it right.
Also mention using TAs and tutors as a resource. "Figure it out" gives off the impression that they may feel they may be on their own

2023-08-15 12:56 UTC, NathanBarta commented on src/guides/academics/succeed-in-course-x/succeed-in-1501.md
> +      - Distance metric
Yeah, we'll have to keep our eyes on it.

2023-08-15 14:54 UTC, FishOfPitt116 approved these changes

2023-08-22 12:36 UTC, merged