Create PM article
pittcsc/pittcswiki pull request #400
Opened 2024-04-20 05:44 UTC by rohit-ganguly

closes #207 #397 

Finally lol, an article on Product Management. I wanted to take a fundamentals approach as opposed to focusing on what the role actually does (enough of the '6 figures without coding' yapping online!!)

2024-04-21 00:50 UTC, NathanBarta requested changes

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +Product Management looks different *everywhere*. Sticking to the fundamentals will take you very far in your PM career no matter what exactly Product looks like in your organization.
"no matter what exactly Product looks like in your organization" -> "no matter what the role looks like in your organization"

Ease of reading. Would this edit make sense?

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +- Who (exactly) are we building this for?
I'd suggest bolding "Who", "What", "Why". 

Idk what you mean be "(exactly)", you also used that word in the previous section, so is it important?

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +In the scope of an engineering team, the job of the Product Manager is to clarify the work to be done, and have a clear reason why. You aren't the one defining how the problem gets solved at the end
"result" -> "product" or "solution"?

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +### The first fundamental
Doesn't follow capitalization scheme

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +### The second fundamental
Doesn't follow capitalization scheme

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +My personal approach is to start backwards and always ask questions. What makes your company money? For Netflix, when focusing on customer features, it's  membership fees. Why do customers pay money
Extraneous space between "it's" and "membership"

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +Understanding how your business makes money, now what are the higher ups saying strategy-wise? What can your product do to align with  overall business goals? While you represent the customers, you a
Extraneous space between "with" and "overall"

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +You'll eventually bring your prioritized ideas to your stakeholders (design, engineering, leadership, etc) and they'll have their own thoughts on the question they're responsible for, *how* do we get
"thoughts on the question" seems kinda out of place

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +You'll eventually bring your prioritized ideas to your stakeholders (design, engineering, leadership, etc) and they'll have their own thoughts on the question they're responsible for, *how* do we get
What's "it"?

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +The most important thing is adjusting your ideas with impact/effort. Again, you are not responsible for ideating a solution - your job is to ensure that there is value provided to customers at the en
"ideas with impact/effort"

Is "with" the right word?

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +At the end of it all, you'll have to prioritize scoped features (features that have had their effort to build measured). Ideally you go for low-effort high-impact features first, and work your way ba
Maybe bring up the concept of "scope" in the first paragraph of this section when you are talking about the other stakeholders.

2024-04-21 00:50 UTC, NathanBarta commented on src/guides/career/product-management.md
> +### Ideation
Title scheme not followed. Should be "Problem Ideation".

2024-04-21 00:53 UTC, NathanBarta commented
Looks good! Definitely fills a hole in the wiki content, so thank you for the contribution! 

I've left a few minor comments, feel free to ping me if you need clarification on any of them or if you'd like to discuss.

2024-04-22 10:55 UTC, rohit-ganguly commented
> Looks good! Definitely fills a hole in the wiki content, so thank you for the contribution!
> 
> I've left a few minor comments, feel free to ping me if you need clarification on any of them or if you'd like to discuss.

Addressed your feedback - let me know your thoughts! Thanks :)

2024-04-23 01:26 UTC, NathanBarta commented on src/guides/career/product-management.md
> +Ideally, this is a pretty straightforward answer once you have a good understanding of the problems to solve. This generally can be prioritized by looking at why you're building it. If you're buildin
Paragraph confuses me. Did you mean "answered" instead of "prioritized" in sentence 2?

2024-04-23 01:36 UTC, merged